// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Museum.Paleontology.Data;

#nullable disable

namespace Museum.Paleontology.Migrations
{
    [DbContext(typeof(MuseumContext))]
    [Migration("20260324132934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Museum.Paleontology.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Фоссилии динозавров",
                            Name = "Динозавры Мезозоя"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ранние млекопитающие",
                            Name = "Млекопитающие Палеогена"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ихтиозавры, плезиозавры, крокодилы",
                            Name = "Морские Рептилии"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Переходные формы",
                            Name = "Археоптерикс и Ранние Птицы"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Трилобиты, кораллы, древние рыбы",
                            Name = "Палеозойские Окаменелости"
                        });
                });

            modelBuilder.Entity("Museum.Paleontology.Models.Fossil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DiscoveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Fossils");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollectionId = 1,
                            Description = "Найден в Монтане",
                            DiscoveryDate = new DateTime(1902, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Череп Тираннозавра",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            CollectionId = 1,
                            Description = "Полный череп",
                            DiscoveryDate = new DateTime(1889, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Череп Трицератопса",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 3,
                            CollectionId = 2,
                            Description = "Из Лос-Анджелеса",
                            DiscoveryDate = new DateTime(1912, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "Клы саблезубого",
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 4,
                            CollectionId = 3,
                            Description = "Полный скелет, отличная сохранность",
                            DiscoveryDate = new DateTime(1821, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Скелет Ихтиозавра",
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 5,
                            CollectionId = 3,
                            Description = "Один из первых найденных",
                            DiscoveryDate = new DateTime(1821, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Скелет Плезиозавра",
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 6,
                            CollectionId = 4,
                            Description = "Доказательство эволции птиц",
                            DiscoveryDate = new DateTime(1861, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            Name = "Перохеоптерикса",
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 7,
                            CollectionId = 1,
                            Description = "Полный набор пластин",
                            DiscoveryDate = new DateTime(1877, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Панцирь Стегозавра",
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 8,
                            CollectionId = 1,
                            Description = "Один из первых находок в Монголии",
                            DiscoveryDate = new DateTime(1924, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Коготь Велоцираптора",
                            SpeciesId = 8
                        },
                        new
                        {
                            Id = 9,
                            CollectionId = 1,
                            Description = "Сохранённый череп с костяным шлемом",
                            DiscoveryDate = new DateTime(1908, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Череп Анкилозавра",
                            SpeciesId = 9
                        },
                        new
                        {
                            Id = 10,
                            CollectionId = 1,
                            Description = "Огромный позвонок",
                            DiscoveryDate = new DateTime(1903, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Позвонок Брахиозавра",
                            SpeciesId = 10
                        },
                        new
                        {
                            Id = 11,
                            CollectionId = 1,
                            Description = "Характерный изогнутый коготь",
                            DiscoveryDate = new DateTime(1964, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Коготь Дейнониха",
                            SpeciesId = 11
                        },
                        new
                        {
                            Id = 12,
                            CollectionId = 1,
                            Description = "Длинный конический зуб",
                            DiscoveryDate = new DateTime(1912, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Зуб Спинозавра",
                            SpeciesId = 12
                        },
                        new
                        {
                            Id = 13,
                            CollectionId = 1,
                            Description = "Хорошо сохранившаяся кость",
                            DiscoveryDate = new DateTime(1877, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Череп Аллозавра",
                            SpeciesId = 13
                        },
                        new
                        {
                            Id = 14,
                            CollectionId = 1,
                            Description = "Первый описанный динозавр",
                            DiscoveryDate = new DateTime(1676, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Череп Мегалозавра",
                            SpeciesId = 14
                        },
                        new
                        {
                            Id = 15,
                            CollectionId = 1,
                            Description = "Сравнение с тираннозавром",
                            DiscoveryDate = new DateTime(1993, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Зуб Гиганотозавра",
                            SpeciesId = 15
                        },
                        new
                        {
                            Id = 16,
                            CollectionId = 1,
                            Description = "Длинный шейный позвонок",
                            DiscoveryDate = new DateTime(1877, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Шейный позвонок Диплодока",
                            SpeciesId = 16
                        },
                        new
                        {
                            Id = 17,
                            CollectionId = 1,
                            Description = "Маленький хищник",
                            DiscoveryDate = new DateTime(1859, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Скелет Компсогната",
                            SpeciesId = 17
                        },
                        new
                        {
                            Id = 18,
                            CollectionId = 1,
                            Description = "Часть скелета раннего динозавра",
                            DiscoveryDate = new DateTime(1834, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Позвонок Платеозавра",
                            SpeciesId = 18
                        },
                        new
                        {
                            Id = 19,
                            CollectionId = 5,
                            Description = "Характерный парус на спине",
                            DiscoveryDate = new DateTime(1878, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Парус Диметродона",
                            SpeciesId = 19
                        },
                        new
                        {
                            Id = 20,
                            CollectionId = 2,
                            Description = "Длинные когти и зубы",
                            DiscoveryDate = new DateTime(1926, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            Name = "Клы Тилакосмила",
                            SpeciesId = 20
                        },
                        new
                        {
                            Id = 21,
                            CollectionId = 3,
                            Description = "Крупный морской рептилий",
                            DiscoveryDate = new DateTime(1780, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Череп Мозазавра",
                            SpeciesId = 21
                        },
                        new
                        {
                            Id = 22,
                            CollectionId = 3,
                            Description = "Очень длинная шея",
                            DiscoveryDate = new DateTime(1868, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Шея Эласмозавра",
                            SpeciesId = 22
                        },
                        new
                        {
                            Id = 23,
                            CollectionId = 3,
                            Description = "Массивный зуб хищника",
                            DiscoveryDate = new DateTime(1873, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Зуб Лиоплевродона",
                            SpeciesId = 23
                        },
                        new
                        {
                            Id = 24,
                            CollectionId = 3,
                            Description = "Ранний морской рептилий",
                            DiscoveryDate = new DateTime(1834, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Скелет Нотозавра",
                            SpeciesId = 24
                        },
                        new
                        {
                            Id = 25,
                            CollectionId = 3,
                            Description = "Крупная хищная рыба",
                            DiscoveryDate = new DateTime(1870, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Скелет Ксифактинуса",
                            SpeciesId = 25
                        },
                        new
                        {
                            Id = 26,
                            CollectionId = 5,
                            Description = "Массивная бронированная рыба",
                            DiscoveryDate = new DateTime(1867, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Голова Дунклеостеуса",
                            SpeciesId = 26
                        },
                        new
                        {
                            Id = 27,
                            CollectionId = 3,
                            Description = "Длинный шип на позвоночнике",
                            DiscoveryDate = new DateTime(1837, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            Name = "Позвонок Ортаканта",
                            SpeciesId = 27
                        },
                        new
                        {
                            Id = 28,
                            CollectionId = 5,
                            Description = "Морской скорпион",
                            DiscoveryDate = new DateTime(1822, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Эвриптерид",
                            SpeciesId = 28
                        },
                        new
                        {
                            Id = 29,
                            CollectionId = 5,
                            Description = "Обычная форма палеозоя",
                            DiscoveryDate = new DateTime(1824, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Трилобит",
                            SpeciesId = 29
                        },
                        new
                        {
                            Id = 30,
                            CollectionId = 5,
                            Description = "Спиральный моллюск",
                            DiscoveryDate = new DateTime(1804, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 5,
                            Name = "Аммонит",
                            SpeciesId = 30
                        },
                        new
                        {
                            Id = 31,
                            CollectionId = 1,
                            Description = "Один из самых высоких динозавров",
                            DiscoveryDate = new DateTime(1994, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Name = "Скелет Сауропозейдона",
                            SpeciesId = 31
                        });
                });

            modelBuilder.Entity("Museum.Paleontology.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Notes = "Динозавры",
                            RoomNumber = "Зал 2"
                        },
                        new
                        {
                            Id = 2,
                            Notes = "Млекопитающие",
                            RoomNumber = "Зал 4"
                        },
                        new
                        {
                            Id = 3,
                            Notes = "Морские рептилии",
                            RoomNumber = "Зал 3"
                        },
                        new
                        {
                            Id = 4,
                            Notes = "Археоптерикс",
                            RoomNumber = "Зал 1"
                        },
                        new
                        {
                            Id = 5,
                            Notes = "Палеозой",
                            RoomNumber = "Зал 5"
                        });
                });

            modelBuilder.Entity("Museum.Paleontology.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommonName = "Тираннозавр",
                            Era = "Поздний мел",
                            LatinName = "Tyrannosaurus rex"
                        },
                        new
                        {
                            Id = 2,
                            CommonName = "Трицератопс",
                            Era = "Поздний мел",
                            LatinName = "Triceratops horridus"
                        },
                        new
                        {
                            Id = 3,
                            CommonName = "Саблезубый кот",
                            Era = "Плейстоцен",
                            LatinName = "Smilodon fatalis"
                        },
                        new
                        {
                            Id = 4,
                            CommonName = "Ихтиозавр",
                            Era = "Ранняя юра",
                            LatinName = "Ichthyosaurus communis"
                        },
                        new
                        {
                            Id = 5,
                            CommonName = "Плезиозавр",
                            Era = "Ранняя юра",
                            LatinName = "Plesiosaurus dolichodeirus"
                        },
                        new
                        {
                            Id = 6,
                            CommonName = "Археоптерикс",
                            Era = "Поздняя юра",
                            LatinName = "Archaeopteryx lithographica"
                        },
                        new
                        {
                            Id = 7,
                            CommonName = "Стегозавр",
                            Era = "Поздняя юра",
                            LatinName = "Stegosaurus armatus"
                        },
                        new
                        {
                            Id = 8,
                            CommonName = "Велоцираптор",
                            Era = "Поздний мел",
                            LatinName = "Velociraptor mongoliensis"
                        },
                        new
                        {
                            Id = 9,
                            CommonName = "Анкилозавр",
                            Era = "Поздний мел",
                            LatinName = "Ankylosaurus magniventris"
                        },
                        new
                        {
                            Id = 10,
                            CommonName = "Брахиозавр",
                            Era = "Поздняя юра",
                            LatinName = "Brachiosaurus altithorax"
                        },
                        new
                        {
                            Id = 11,
                            CommonName = "Дейноних",
                            Era = "Ранняя мел",
                            LatinName = "Deinonychus antirrhopus"
                        },
                        new
                        {
                            Id = 12,
                            CommonName = "Спинозавр",
                            Era = "Поздний мел",
                            LatinName = "Spinosaurus aegyptiacus"
                        },
                        new
                        {
                            Id = 13,
                            CommonName = "Аллозавр",
                            Era = "Поздняя юра",
                            LatinName = "Allosaurus fragilis"
                        },
                        new
                        {
                            Id = 14,
                            CommonName = "Мегалозавр",
                            Era = "Средняя юра",
                            LatinName = "Megalosaurus bucklandii"
                        },
                        new
                        {
                            Id = 15,
                            CommonName = "Гиганотозавр",
                            Era = "Поздний мел",
                            LatinName = "Giganotosaurus carolinii"
                        },
                        new
                        {
                            Id = 16,
                            CommonName = "Диплодок",
                            Era = "Поздняя юра",
                            LatinName = "Diplodocus carnegii"
                        },
                        new
                        {
                            Id = 17,
                            CommonName = "Компсогнат",
                            Era = "Поздняя юра",
                            LatinName = "Compsognathus longipes"
                        },
                        new
                        {
                            Id = 18,
                            CommonName = "Платеозавр",
                            Era = "Поздний триас",
                            LatinName = "Plateosaurus engelhardti"
                        },
                        new
                        {
                            Id = 19,
                            CommonName = "Диметродон",
                            Era = "Ранний пермь",
                            LatinName = "Dimetrodon grandis"
                        },
                        new
                        {
                            Id = 20,
                            CommonName = "Тилакосмил",
                            Era = "Поздний Миоцен - Ранний Плиоцен",
                            LatinName = "Thylacosmilus atrox"
                        },
                        new
                        {
                            Id = 21,
                            CommonName = "Мозазавр",
                            Era = "Поздний мел",
                            LatinName = "Mosasaurus hoffmannii"
                        },
                        new
                        {
                            Id = 22,
                            CommonName = "Эласмозавр",
                            Era = "Поздний мел",
                            LatinName = "Elasmosaurus platyurus"
                        },
                        new
                        {
                            Id = 23,
                            CommonName = "Лиоплевродон",
                            Era = "Средняя юра",
                            LatinName = "Liopleurodon ferox"
                        },
                        new
                        {
                            Id = 24,
                            CommonName = "Нотозавр",
                            Era = "Ранний триас",
                            LatinName = "Nothosaurus giganteus"
                        },
                        new
                        {
                            Id = 25,
                            CommonName = "Ксифактинус",
                            Era = "Поздний мел",
                            LatinName = "Xiphactinus audax"
                        },
                        new
                        {
                            Id = 26,
                            CommonName = "Дунклеостеус",
                            Era = "Поздний девон",
                            LatinName = "Dunkleosteus terrelli"
                        },
                        new
                        {
                            Id = 27,
                            CommonName = "Ортакантус",
                            Era = "Каменноугольный - Пермский",
                            LatinName = "Orthacanthus compressus"
                        },
                        new
                        {
                            Id = 28,
                            CommonName = "Эвриптерид",
                            Era = "Силурий",
                            LatinName = "Eurypterid"
                        },
                        new
                        {
                            Id = 29,
                            CommonName = "Трилобит",
                            Era = "Кембрий - Пермский",
                            LatinName = "Trilobita"
                        },
                        new
                        {
                            Id = 30,
                            CommonName = "Аммонит",
                            Era = "Девон - Мел",
                            LatinName = "Ammonite"
                        },
                        new
                        {
                            Id = 31,
                            CommonName = "Сауропозейдон",
                            Era = "Поздний мел",
                            LatinName = "Sauroposeidon proteles"
                        });
                });

            modelBuilder.Entity("Museum.Paleontology.Models.Fossil", b =>
                {
                    b.HasOne("Museum.Paleontology.Models.Collection", "Collection")
                        .WithMany("Fossils")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Museum.Paleontology.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Museum.Paleontology.Models.Species", "Species")
                        .WithMany("Fossils")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Location");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Museum.Paleontology.Models.Collection", b =>
                {
                    b.Navigation("Fossils");
                });

            modelBuilder.Entity("Museum.Paleontology.Models.Species", b =>
                {
                    b.Navigation("Fossils");
                });
#pragma warning restore 612, 618
        }
    }
}
